
import type { Branch, BranchStatus, Service } from './types';

export const branches: Branch[] = [
  {
    id: 'gdl-centro',
    name: 'Grupo Naser - Guadalajara Centro',
    address: 'Av. Hidalgo 472, Zona Centro, 44100 Guadalajara, Jal.',
    city: 'Guadalajara',
    state: 'Jalisco',
    coordinates: { lat: 20.678, lng: -103.353 },
    phone: '33-1234-5678',
    emergencyPhone: '33-9876-5432',
    schedule: 'Abierto 24 horas',
    services: ['Velación', 'Cremación', 'Traslados'],
    status: 'urgencias',
    imageUrl: 'https://placehold.co/600x400.png',
    manager: 'Carlos Mendoza',
  },
  {
    id: 'cdmx-reforma',
    name: 'Grupo Naser - Reforma',
    address: 'Paseo de la Reforma 222, Juárez, 06600 Ciudad de México, CDMX',
    city: 'Ciudad de México',
    state: 'CDMX',
    coordinates: { lat: 19.435, lng: -99.16 },
    phone: '55-5555-5555',
    schedule: 'L-V 9:00 - 18:00',
    services: ['Gestoría', 'Capillas'],
    status: 'activa',
    imageUrl: 'https://placehold.co/600x400.png',
    manager: 'Ana Sofía Paredes',
  },
  {
    id: 'mty-san-pedro',
    name: 'Grupo Naser - San Pedro',
    address: 'Av. José Vasconcelos 402, Del Valle, 66220 San Pedro Garza García, N.L.',
    city: 'Monterrey',
    state: 'Nuevo León',
    coordinates: { lat: 25.659, lng: -100.37 },
    phone: '81-8765-4321',
    emergencyPhone: '81-1234-5678',
    schedule: 'Abierto 24 horas',
    services: ['Velación', 'Embalsamamiento', 'Capillas', 'Cremación'],
    status: 'urgencias',
    imageUrl: 'https://placehold.co/600x400.png',
    manager: 'Ricardo Fernandez',
  },
  {
    id: 'cancun-playa',
    name: 'Grupo Naser - Cancún Playa',
    address: 'Blvd. Kukulcan Km 9.5, Zona Hotelera, 77500 Cancún, Q.R.',
    city: 'Cancún',
    state: 'Quintana Roo',
    coordinates: { lat: 21.134, lng: -86.772 },
    phone: '998-111-2233',
    schedule: 'Cita Previa',
    services: ['Gestoría', 'Traslados'],
    status: 'proxima',
    imageUrl: 'https://placehold.co/600x400.png',
    manager: 'Lucía Reyes',
  },
    {
    id: 'tijuana-zona-rio',
    name: 'Grupo Naser - Tijuana Zona Río',
    address: 'P.º de los Héroes 9350, Zona Urbana Rio, 22010 Tijuana, B.C.',
    city: 'Tijuana',
    state: 'Baja California',
    coordinates: { lat: 32.528, lng: -117.021 },
    phone: '664-987-6543',
    schedule: 'L-S 8:00 - 20:00',
    services: ['Velación', 'Cremación'],
    status: 'activa',
    imageUrl: 'https://placehold.co/600x400.png',
    manager: 'Jorge Valenzuela',
  },
  {
    id: 'merida-norte',
    name: 'Grupo Naser - Mérida Norte',
    address: 'Calle 60 299, Zona Paseo Montejo, 97000 Mérida, Yuc.',
    city: 'Mérida',
    state: 'Yucatán',
    coordinates: { lat: 20.985, lng: -89.622 },
    phone: '999-555-1234',
    schedule: 'Cerrado permanentemente',
    services: [],
    status: 'inactiva',
    imageUrl: 'https://placehold.co/600x400.png',
    manager: 'N/A',
  },
];

export const allServices: Service[] = ["Velación", "Cremación", "Traslados", "Embalsamamiento", "Capillas", "Gestoría"];

export const allStatuses: BranchStatus[] = ["activa", "inactiva", "proxima", "urgencias"];
